# Generated by Django 3.2.8 on 2021-12-15 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preg1', models.IntegerField(choices=[[0, 'muy mal'], [1, 'mal'], [2, 'normal'], [3, 'bien'], [4, 'muy bien']])),
                ('preg2', models.IntegerField(choices=[[2, 'capaz'], [1, 'quizas'], [0, 'incapaz']])),
                ('preg3', models.IntegerField(choices=[[0, 'muy mal'], [1, 'mal'], [2, 'normal'], [3, 'bien'], [4, 'muy bien']])),
                ('preg4', models.IntegerField(choices=[[0, 'mucho'], [1, 'me  preocupa'], [2, 'poco '], [3, 'no me afecta']])),
                ('preg5', models.IntegerField(choices=[[0, 'Muy presionado'], [1, 'poco presionado'], [2, 'Ninguna presión']])),
                ('preg6', models.IntegerField(choices=[[0, 'Si'], [1, 'No']])),
                ('preg7', models.IntegerField(choices=[[0, 'siempre'], [1, 'casi siempre'], [2, 'a veces'], [3, 'casi nunca'], [4, 'nunca']])),
                ('preg8', models.IntegerField(choices=[[0, 'siempre'], [1, 'casi siempre'], [2, 'a veces'], [3, 'casi nunca'], [4, 'nunca']])),
                ('preg9', models.IntegerField(choices=[[0, 'Me cuesta mucho'], [1, 'Me cuesta poco'], [2, 'Me relajo fácilmente']])),
                ('preg10', models.IntegerField(choices=[[0, 'mucho'], [1, 'más o menos'], [2, 'poco'], [3, 'nada']])),
                ('preg11', models.IntegerField(choices=[[0, 'mucho'], [1, 'más o menos'], [2, 'poco'], [3, 'nada'], [4, 'saltar']])),
                ('preg12', models.IntegerField(choices=[[0, 'Ha sido peor'], [1, 'Igual que la semana anterior'], [2, 'Un poco mejor'], [3, 'Ha mejorado mucho ']])),
                ('preg13', models.IntegerField(choices=[[0, 'Casi no puedo dormir'], [1, 'Duermo mucho más que antes'], [2, 'Duermo un poco menos'], [3, 'Estoy durmiendo un poco más'], [4, 'Duermo lo mismo que siempre']])),
                ('preg14', models.IntegerField(choices=[[0, 'Siento que tengo muy poco tiempo'], [1, 'Siento que estoy bien con el tiempo '], [2, 'Me siento con mucho tiempo libre']])),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('puntaje', models.CharField(blank=True, max_length=4, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
