# Generated by Django 3.2.8 on 2021-11-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preg1', models.IntegerField(choices=[[0, 'muy mal'], [1, 'mal'], [2, 'normal'], [3, 'bien'], [4, 'muy bien']])),
                ('preg2', models.IntegerField(choices=[[0, 'capaz'], [1, 'quizas'], [2, 'incapaz']])),
                ('preg3', models.IntegerField(choices=[[0, 'muy mal'], [1, 'mal'], [2, 'normal'], [3, 'bien'], [4, 'muy bien']])),
                ('preg4', models.IntegerField(choices=[[0, 'mucho'], [1, 'me  preocupa'], [2, 'poco '], [3, 'no me afecta']])),
                ('preg5', models.IntegerField(choices=[[0, 'Muy presionado'], [1, 'poco presionado'], [2, 'Ninguna presión']])),
                ('preg6', models.IntegerField(choices=[[0, 'Si'], [1, 'No']])),
                ('preg7', models.IntegerField(choices=[[0, 'siempre'], [1, 'casi siempre'], [2, 'a veces'], [3, 'casi nunca'], [4, 'nunca']])),
                ('preg8', models.IntegerField(choices=[[0, 'siempre'], [1, 'casi siempre'], [2, 'a veces'], [3, 'casi nunca'], [4, 'nunca']])),
                ('preg9', models.IntegerField(choices=[[0, 'Me cuesta mucho'], [1, 'Me cuesta poco'], [2, 'Me relajo fácilmente']])),
                ('preg10', models.IntegerField(choices=[[0, 'mucho'], [1, 'más o menos'], [2, 'poco'], [3, 'nada']])),
                ('preg11', models.IntegerField(choices=[[0, 'mucho'], [1, 'más o menos'], [2, 'poco'], [3, 'nada'], [4, 'saltar']])),
                ('preg12', models.IntegerField(choices=[[0, 'Ha sido peor'], [1, 'Un poco mejor'], [2, 'igual que la semana anterior'], [3, 'Ha mejorado mucho ']])),
                ('preg13', models.IntegerField(choices=[[0, 'Casi no puedo dormir'], [1, 'Duermo un poco menos'], [2, 'duermo lo mismo que siempre'], [3, 'estoy durmiendo un poco más'], [4, 'Duermo mucho más que antes']])),
                ('preg14', models.IntegerField(choices=[[0, 'Siento que tengo muy poco tiempo'], [1, 'Siento que estoy bien con el tiempo '], [2, 'Me siento con mucho tiempo libre']])),
            ],
        ),
    ]
