# Generated by Django 3.2.8 on 2021-11-04 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
