# Generated by Django 3.2.8 on 2021-11-11 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0003_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='name',
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
