# Generated by Django 3.2.8 on 2021-11-27 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20211127_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formu',
            name='preg2',
            field=models.IntegerField(choices=[[2, 'capaz'], [1, 'quizas'], [0, 'incapaz']]),
        ),
        migrations.AlterField(
            model_name='formu',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 11, 27), null=True),
        ),
    ]
