# Generated by Django 3.2.8 on 2021-11-27 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20211127_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formu',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 27, 19, 40, 31, 202002, tzinfo=utc), null=True),
        ),
    ]
