# Generated by Django 3.2.8 on 2021-11-30 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20211130_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formu',
            name='puntaje',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='formu',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 30, 23, 50, 57, 847705, tzinfo=utc), null=True),
        ),
    ]
