# Generated by Django 3.2.8 on 2021-11-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20211111_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preg1', models.IntegerField(choices=[[0, 'muy mal'], [1, 'mal'], [2, 'normal'], [3, 'bien'], [4, 'muy bien']])),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
