# Generated by Django 3.2.9 on 2021-11-23 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20211111_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
