# Generated by Django 3.2.8 on 2021-11-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20211121_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='formu',
            name='a',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
