# Generated by Django 3.2.8 on 2021-11-30 23:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20211130_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formu',
            name='puntaje',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='formu',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 30, 23, 59, 19, 572753, tzinfo=utc), null=True),
        ),
    ]
