# Generated by Django 3.2.8 on 2021-12-01 00:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20211130_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='formu',
            name='Ncuest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='formu',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 1, 0, 11, 6, 449802, tzinfo=utc), null=True),
        ),
    ]
