# Generated by Django 3.2.8 on 2021-11-23 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0009_alter_formu_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='formu',
            name='preg3',
            field=models.IntegerField(choices=[[0, 'muy mal'], [1, 'mal'], [2, 'normal'], [3, 'bien'], [4, 'muy bien']], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formu',
            name='a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
