# Generated by Django 3.2.8 on 2021-12-01 00:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20211130_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formu',
            name='Ncuest',
        ),
        migrations.AlterField(
            model_name='formu',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 1, 0, 17, 37, 393910, tzinfo=utc), null=True),
        ),
    ]
