# Generated by Django 3.2.8 on 2021-12-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20211130_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formu',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
