# Generated by Django 3.2.8 on 2021-11-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20211122_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='formu',
            name='preg10',
            field=models.IntegerField(choices=[[0, 'mucho'], [1, 'más o menos'], [2, 'poco'], [3, 'nada']], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='preg11',
            field=models.IntegerField(choices=[[0, 'mucho'], [1, 'más o menos'], [2, 'poco'], [3, 'nada'], [4, 'saltar']], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='preg12',
            field=models.IntegerField(choices=[[0, 'Ha sido peor'], [1, 'Un poco mejor'], [2, 'igual que la semana anterior'], [3, 'Ha mejorado mucho ']], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='preg13',
            field=models.IntegerField(choices=[[0, 'Casi no puedo dormir'], [1, 'Duermo un poco menos'], [2, 'duermo lo mismo que siempre'], [3, 'estoy durmiendo un poco más'], [4, 'Duermo mucho más que antes']], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='preg14',
            field=models.IntegerField(choices=[[0, 'Siento que tengo muy poco tiempo'], [1, 'Siento que estoy bien con el tiempo '], [2, 'Me siento con mucho tiempo libre']], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='preg2',
            field=models.IntegerField(choices=[[0, 'capaz'], [1, 'quizas'], [2, 'incapaz']], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='preg4',
            field=models.IntegerField(choices=[[0, 'mucho'], [1, 'me  preocupa'], [2, 'poco '], [3, 'no me afecta']], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='preg5',
            field=models.IntegerField(choices=[[0, 'Muy presionado'], [1, 'poco presionado'], [2, 'Ninguna presión']], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='preg6',
            field=models.IntegerField(choices=[[0, 'Si'], [1, 'No']], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='preg7',
            field=models.IntegerField(choices=[[0, 'siempre'], [1, 'casi siempre'], [2, 'a veces'], [3, 'casi nunca'], [4, 'nunca']], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='preg8',
            field=models.IntegerField(choices=[[0, 'siempre'], [1, 'casi siempre'], [2, 'a veces'], [3, 'casi nunca'], [4, 'nunca']], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formu',
            name='preg9',
            field=models.IntegerField(choices=[[0, 'Me cuesta mucho'], [1, 'Me cuesta poco'], [2, 'Me relajo fácilmente']], default=0),
            preserve_default=False,
        ),
    ]
