# Generated by Django 3.2.8 on 2021-11-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20211122_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formu',
            name='a',
        ),
    ]
