# Generated by Django 3.2.8 on 2021-11-23 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_formu_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formu',
            name='user',
        ),
    ]
