# Generated by Django 3.2.8 on 2021-11-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_delete_usuario'),
        ('usuarios', '0015_remove_formu_user'),
    ]

    operations = [
    ]
